- name: wipe of a web app
  block:
    - name: Stop and remove Docker container
      docker_container:
        name: "{{ my_web_app }}"
        state: absent
  when: web_app_full_wipe | bool
  tags:
    - wipe