- name: Web App Tasks
  block:
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_image_tag }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ my_web_app }}"
        image: "{{ docker_image }}"
        state: started
        ports:
          - "{{ 5000 }}:{{ 5000 }}"

    - name: Wipe Docker container
      import_tasks: tasks/0-wipe.yml
      vars:
        web_app_full_wipe: true

  tags:
    - web_app