- name: Render docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ image_dir }}/docker-compose.yml"
  vars:
    image_full: "{{image_name}}:{{image_tag}}"
    publish_ports: "{{ ports }}"
- name: Start  docker
  service:
    name: "docker"
    state: "started"
    enabled: true
- name: Start app service
  community.docker.docker_compose_v2:
    project_src: "{{ image_dir }}"
    state: "present"
    remove_orphans: true

- name: Wipe Docker container
  import_tasks: tasks/0-wipe.yml
  vars:
    web_app_full_wipe: true