- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install python
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Docker Compose using pip
  pip:
    name: docker-compose
    state: present