name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:23.0.3
        options: --privileged

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask gunicorn pytz

      - name: Lint code
        run: |
          flake8 .

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p '*_test.py'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t your-image-name .

      - name: Push Docker image to registry
        run: |
          docker push your-image-name

      - name: Install Snyk CLI
        run: pip install snyk

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_API_TOKEN }}

      - name: Run Snyk Vulnerability Scan
        run: snyk test --all-projects
